### ISSUE TITLE
No API to retrieve original channel layout of CAF file

### ISSUE THREAD

**Issue by nu774** [dbry/WavPack#14]
Some CAF channel layouts (with Microsoft channel order) are translated into channel mask and that's OK, but others are not.
Currently, only way to know the original channel layout is to retrieve the CAF wrapper (assuming -r is not set when encoding), then to manually parse it. 

Can we have an API to retrieve CAF style channel layout? Since WAV channel mask can also be described in CAF style channel layout (with kAudioChannelLayoutTag_UseChannelBitmap), it can serve as a super set API not only for the CAF wrapper.

Alternatively, some layouts such as kAudioChannelLayoutTag_MPEG_5_0_B (L R Ls Rs C) that are only different in channel order from WAV equivalent can be supported using channel mask + automatic channel mapping on the decoding time. This may not be a perfect solution, but existing applications are not required any modifications to support them, and most of the layouts can be supported this way.

**Comment by dbry** [comment]
It's hard for me to believe, but I actually did that CAF parsing code almost 7 years ago! Needless to say, I have forgotten what exactly I had in mind for the channel mapping stuff, but I agree that forcing an app to parse the CAF header to figure out the channel configuration is not acceptable. I'll look into it and come up with a proposal. Thanks for pointing this out!

**Comment by dbry** [comment]
Okay, I think have this covered. I accept the channel layouts that are not in Microsoft order by reordering them to Microsoft order and storing the MS channel mask, Core Audio layout ID and the reorder information in the file. If an application does not care about layouts then the file will decode in Microsoft order, but an application that does care can obtain the layout ID and also a string indicating how the channels should be reordered to match the original file (and match the MD5).

If a file uses the description array I also handle that now, but I don't do any reordering, so only those channels that appear in MS order will be in the channel mask. Hopefully extensive use of this is not too common!

Thanks again for pointing this out!
