### ISSUE TITLE
Increase `cmake_minimum_required` version

### ISSUE THREAD

**Issue by redtide** [dbry/WavPack#162]
We get this warning during configuration:
```
 CMake Deprecation Warning at external/st_audiofile/thirdparty/wavpack/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```
It would be possible to increase it from 3.2 to 3.5?

**Comment by dbry** [comment]
I think that would be fine. Any issues @evpobr or @SoapGentoo or @sezero ?

Thanks!

**Comment by sezero** [comment]
> I think that would be fine. Any issues @evpobr or @SoapGentoo or @sezero ?

No issues from me, although the following would silence that warning too, which we did in several projects: (@madebr may have more to say.)

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,2 +1,2 @@
-cmake_minimum_required(VERSION 3.2)
+cmake_minimum_required(VERSION 3.2...3.5)
 
```

**Comment by SoapGentoo** [comment]
@dbry sure, we're always very on top of things, and those are very old cmake releases, so go ahead

**Comment by evpobr** [comment]
Hi, I think it's ok.

**Comment by redtide** [comment]
> > I think that would be fine. Any issues @evpobr or @SoapGentoo or @sezero ?
> 
> No issues from me, although the following would silence that warning too, which we did in several projects: (@madebr may have more to say.)
> 
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -1,2 +1,2 @@
> -cmake_minimum_required(VERSION 3.2)
> +cmake_minimum_required(VERSION 3.2...3.5)
>  
> ```

which it seems what the message suggests with `...or use a ...<max>...`.
To be precise I don't care about the warning per se, just not want that something gets broken in future all of the sudden, which for an Archlinux (or any other rolling release distribution) user could be even tomorrow :P

**Comment by dbry** [comment]
Thanks everyone!

**Comment by redtide** [comment]
Thank you!
