### ISSUE TITLE
exceeded number of channels with only 384

### ISSUE THREAD

**Issue by agbondy** [dbry/WavPack#183]
Hi!

The documentation for the latest release of wavpack says that it supports raw pcm data with up to 4096 channels. However, I can't seem to use the linux command line tool for my data if I specify any more than 256 channels (the data in fact has 384 channels).

`wavpack --raw-pcm=30000,16,384 myfile.bin` gives the following error:  "argument range error in raw PCM specification! "

When the number of channels is set to 256 or below, this error is not raised, suggesting 256 (not 4096) is the maximum number of channels allowed.  Any help or advice would be appreciated. Thanks.

I installed the latest release 5.7.0 from source on linux.

**Comment by agbondy** [comment]
Ah! I see this issue was already discussed in #117. I will locally change the maximum number of allowed channels in cli/wavpack.c and close the issue.  (I have the same neuroscience use case as Alessio described in that issue).

**Comment by dbry** [comment]
You actually don't have to do that either. Just use `--raw-pcm-ex` instead to get the full 4096 channels.

Sorry, that was meant to prevent use of something not well-tested yet, and should probably come out next release.

**Comment by agbondy** [comment]
Thanks, David!
