### ISSUE TITLE
New dependency on wchar_t

### ISSUE THREAD

**Issue by tpetazzoni** [dbry/WavPack#19]
Commit 3ff79bc9150e4b099469ca927a5b64b057eb0200 introduced a new program, ```wvtag```. However, by doing so, it has added a dependency on wchar_t, which until now wasn't used by wavpack on Linux systems. Therefore, with C libraries that don't provide wchar_t support, the build now fails with:

```
import_id3.c:37:34: error: unknown type name 'wchar_t'
 static int WideCharToUTF8 (const wchar_t *Wide, unsigned char *pUTF8, int len);
                                  ^
import_id3.c: In function 'ImportID3v2':
import_id3.c:166:17: error: unknown type name 'wchar_t'
                 wchar_t *wide_string = malloc ((nchars + 1) * sizeof (wchar_t));
                 ^
import_id3.c:166:71: error: 'wchar_t' undeclared (first use in this function)
                 wchar_t *wide_string = malloc ((nchars + 1) * sizeof (wchar_t));
                                                                       ^
import_id3.c:166:71: note: each undeclared identifier is reported only once for each function it appears in
import_id3.c: At top level:
import_id3.c:300:34: error: unknown type name 'wchar_t'
 static int WideCharToUTF8 (const wchar_t *Wide, unsigned char *pUTF8, int len)
                                  ^
import_id3.c: In function 'WideCharToUTF8':
import_id3.c:302:11: error: unknown type name 'wchar_t'
     const wchar_t *pWide = Wide;
```

Should one conclude that wchar support is now mandatory to build wavpack, or is this additional dependency considered as a bug?

**Comment by dbry** [comment]
Thanks for the heads-up on this. I didn't realize (or remember) that some Linux systems don't define wchar_t, but I have (hopefully) eliminated the dependency in master. If it's convenient, please let me know if I missed one, and thanks again!
