### ISSUE TITLE
Compilation errors: wrong types used for _BitScanForward.

### ISSUE THREAD

**Issue by jrlanglois** [dbry/WavPack#24]
In a `_WIN64` context, [`_BitScanForward`](https://docs.microsoft.com/en-us/cpp/intrinsics/bitscanforward-bitscanforward64) is used.

`_BitScanForward` expects types of `unsigned long *`/`unsigned long`, but `uint32_t*`/`uint32_t *` are being fed into it.

I'd like to propose typecasting as a solution:
```c
_BitScanForward ((unsigned long *)&ones_count, (unsigned long)~wps->wvbits.sr);
```

**Comment by dbry** [comment]
Thanks, I assume this is another C++ issue. I'll take a look and maybe create a macro like I do for _BitScanReverse().

**Comment by jrlanglois** [comment]
Not this time I don't think. According to the docs for `_BitScanForward`, [here](https://docs.microsoft.com/en-us/cpp/intrinsics/bitscanforward-bitscanforward64), the prototype is the same in C and C++.

This may simply simply be a shortcoming of TravisCI as you can't test anything on Windows using that system...

**Comment by dbry** [comment]
It's definitely a C++ issue. I created a test program and compiled it for C and C++ (with /TC and /TP respectively):
```
C:\cygwin64\home\david\wavpack-five>type test.c
#include <intrin.h>

int main (void)
{
    unsigned int foo, bar = 17;

    _BitScanForward (&foo, bar);

    return 0;
}

C:\cygwin64\home\david\wavpack-five>cl /TC test.c
Microsoft (R) C/C++ Optimizing Compiler Version 15.00.21022.08 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test.c
Microsoft (R) Incremental Linker Version 9.00.21022.08
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj

C:\cygwin64\home\david\wavpack-five>cl /TP test.c
Microsoft (R) C/C++ Optimizing Compiler Version 15.00.21022.08 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

test.c
test.c(7) : error C2664: '_BitScanForward' : cannot convert parameter 1 from 'unsigned int *' to 'unsigned long *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast

C:\cygwin64\home\david\wavpack-five>
```
I believe this is a little overly pedantic because `unsigned int` and `unsigned long` are _exactly_ the same thing to the Microsoft C/C++ Compiler, which is why the simple cast you suggest would work fine for now.

But _someday_ they might make `long` 64-bits (like on Linux) which would [silently] break that, so I did a slightly more complex fix (and verified that there was no performance penalty).

Thanks!

**Comment by jrlanglois** [comment]
Interesting!

Looking at the problem again, `long` only needs to be _at least_ 32-bits according to the C++ standards - which your recent change encompasses nicely.

Cheers.
