### ISSUE TITLE
Building 4.75.0 on Mac OS 10.10.3 requires `--disable-asm` and `--disable-shared`

### ISSUE THREAD

**Issue by dunn** [dbry/WavPack#3]
Trying to build without both options results in the following errors:

- without `--disable-asm` (Clang): https://gist.github.com/dunn/de2dd3666c9a35bd54e9
- without `--disable-asm` (GCC): https://gist.github.com/dunn/a576a2b16018b902de62
- without `--disable-shared` (Clang): https://gist.github.com/dunn/e2335420bb6622796da2
- without `--disable-shared` (GCC): https://gist.github.com/c03362f2f890ea48097b

**Comment by dbry** [comment]
Thanks for reporting. Unfortunately I have no Mac to work on (so perhaps you could experiment a little for me). I have committed a fix that will hopefully fix the --disable-shared issues (adding a few "extern"s to wavpack_local.h)

I also changed all the "sal" instructions to "shl" to address those errors. The other "asm" errors are not as obvious, but it might work to simply remove the "[rip]" from the "lea r8, log2_buffer [rip]" line (that works on MSVC).

As for the .align errors, my guess is that either they are too large or they require a power of two parameter instead of the byte count. So what I would try first is to change a .align 64 to .align 6 and see if that fixes one error. If so you could change them all (and the .align 256 would become .align 8). If that's not it, then I would try changing them all to .align 16, and then .align 4.

The gcc asm problem completely baffles me. The line numbers don't even seem to match, so I'm not sure how to help there. I will look further at the other files and see if I can see anything else.

Thanks again!

**Comment by dunn** [comment]
Awesome, with 12867b33e2de3e95b88d7cb6f449ce0c5c87cdd5 applied 4.75.0 builds without `--disable-shared`; I'll take a look at the `.align` stuff as soon as I get the chance.

**Comment by dbry** [comment]
Glad to hear it...thanks!

**Comment by dunn** [comment]
Sorry it took me so long to get to this.  `s/64/6` and `s/256/8` got rid of most of the errors; just one left:
```
pack_x64.s:1642:28: error: unexpected token in argument list
        lea r8, log2_table [rip]
                           ^
```
([Full build logs here](https://gist.github.com/dunn/6217a33f09560b7fc729#file-02-make-L74))

**Comment by dbry** [comment]
Thanks for trying that and letting me know!

As for the last issue, did you try just deleting the "[rip]" and leaving "lea r8, log2_table"? That works on MSVC.

The only other thing I can think of is replacing that single instruction with these two:
```
    movabs  rax, OFFSET log2_table
    mov     r8, rax
```

Hopefully one of those alternatives will work.

**Comment by dunn** [comment]
Deleting `[rip]` gives us this ([logs](https://gist.github.com/dunn/098ef949da41d358f16a#file-02-make-L75)):
```
clang -cc1as: fatal error: error in backend: 32-bit absolute addressing is not supported in 64-bit mode
make[1]: *** [pack_x64.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1
```

The other change leads to ([logs](https://gist.github.com/dunn/75684faa92248fff758d#file-02-make-L71)):
```
pack_x64.s:1642:28: error: unexpected token in argument list
        movabs rax, OFFSET log2_table
                           ^
```

**Comment by dbry** [comment]
At this point I'm out of ideas. Maybe there's something fundamental about clang I don't understand. It looks like it doesn't know about rip-relative addressing, even though I read that it's the only supported addressing mode on 64-bit OS X. But maybe it's just an Intel syntax thing (all the examples I find online are AT&T syntax). As stabs in the dark, you might try these, in order:
```
    lea    r8, [log2_table]
    lea    r8, [log2_table+rip]
    lea    r8, [rip+log2_table]
```

Thanks again!

**Comment by dunn** [comment]
All fail, I'm afraid:
- https://gist.github.com/dunn/3ef4ae0785d7b2e58df5#file-02-make-L73
- https://gist.github.com/dunn/eff43c2ed01b1e9a9efd#file-02-make-L82
- https://gist.github.com/dunn/af4748c062dc897604a0#file-02-make-L82

On OS X we'll just build with `--disable-asm`. Thanks for all your help!

**Comment by dbry** [comment]
Hey, not so fast! The second two attempts made it through the assembler without syntax errors and now there's a new batch of errors during the link that are easy to fix (just need to add leading underscores to the asm labels which I already had to do for 32-bit x86). I have pushed both these changes, so it should work now. Thanks again!

**Comment by dunn** [comment]
That did the trick, thanks so much!

Will the `64`/`6` and `256`/`8` substitutions have to remain in perpetuity?

**Comment by lvqcl** [comment]
From https://sourceware.org/binutils/docs/as/Align.html#Align:
>The way the required alignment is specified varies from system to system. For the arc, hppa, i386 using ELF, i860, iq2000, m68k, or1k, s390, sparc, tic4x, tic80 and xtensa, the first expression is the alignment request in bytes. For example `.align 8' advances the location counter until it is a multiple of 8. If the location counter is already a multiple of 8, no change is needed. For the tic54x, the first expression is the alignment request in words. 
>
>For other systems, including ppc, i386 using a.out format, arm and strongarm, it is the number of low-order zero bits the location counter must have after advancement. For example `.align 3' advances the location counter until it a multiple of 8. If the location counter is already a multiple of 8, no change is needed. 
>
>This inconsistency is due to the different behaviors of the various native assemblers for these systems which GAS must emulate. GAS also provides .balign and .p2align directives, described later, which have a consistent behavior across all architectures (but are specific to GAS).

AFAIK OSX assembler supports .p2align, but not .balign. So the possible solution is to replace
.align 256 -> .p2align 8
.align 64 -> .p2align 6
.align 4 -> .p2align 2
In this case it should work in both GNU assembler (aka GAS) and OSX own assembler.

(if OSX asm supports .balign then it's simpler to just replace .align with .balign)

**Comment by dbry** [comment]
I tried `.balign` on Mac OS 10.10.4, Xcode 6.4 and it works (and is not ambiguous), so I've changed all modules to that (hopefully this won't break something else). I also fixed a problem that was causing i386 builds to not work on OS X and squashed some Clang warnings. We should be "good to go" on Mac OS now, so I'll probably be doing a 4.75.2 release incorporating these and other changes. Thanks!

**Comment by dbry** [comment]
Closing as the latest changes allow building on both 32-bit and 64-bit Mac OS.

**Comment by dunn** [comment]
Thanks again!
