### ISSUE TITLE
ChangeLog is heavily out of date

### ISSUE THREAD

**Issue by jrlanglois** [dbry/WavPack#36]
It hasn't been updated since January, 2017.

https://github.com/dbry/WavPack/blob/master/ChangeLog

**Comment by dbry** [comment]
I've recently read that the ChangeLog file is supposed to have more stuff in it than just the release notes, which is what I've been using it for (it matches the "changes" link on my home page). But the last release was January 2017. A _real_ changelog is kind of redundant when there's git's commits log, but I look around at some other repos. Perhaps the existing ChangeLog file should actually go into NEWS?

**Comment by jrlanglois** [comment]
@dbry Though I haven't had the chance to circle back in a while, thanks for looking into the slew of issues I posted!
