### ISSUE TITLE
iconv not found

### ISSUE THREAD

**Issue by OutOfBedlem** [dbry/WavPack#5]
When I have tried to build WavPack under development environment which is separated from os system libraries, wav pack's configure "--with-iconv=$DEV_HOME" can not find libiconv that actually exists in $DEV_HOME/lib

I could fix this problem by adding a line into configure.ac like below...

        diff configure.ac configure.ac.org
        85d84
        < 			CFLAGS="${ICONV_CFLAGS} ${CFLAGS}"

**Comment by dbry** [comment]
Thanks for reporting this! I have to admit that I really don't understand this configure stuff very well, but your change seems to make sense.

However, in that same section there seems to be some stuff to save the old LDFLAGS and LIBS (in old_ldflags, etc). Should I add that for CFLAGS also then? Sorry I'm so clueless about this!  :)

**Comment by OutOfBedlem** [comment]
It seems CFLAGS only problem that I have mentioned.

**Comment by dbry** [comment]
I have committed a fix for this, including your patch line and what I talked about saving CFLAGS. If convenient, please let me know if this works okay. Thanks again for reporting and the patch!

**Comment by OutOfBedlem** [comment]
Thanks, the problem has gone.

**Comment by dbry** [comment]
Thanks. I'll close the issue.
