### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by evpobr** [dbry/WavPack#51]
Why not add it to Autotools? I can develop and maintrain it.

**Comment by dbry** [comment]
I have to admit I'm a little clueless about this. I use CMake at work so I am vaguely familiar with it, but I don't understand what advantage providing CMake to build WavPack would be. I assume that the tarball would still use regular Make by default and that this change would provide an option for the user to select CMake on the configure command-line? Why would they do that? Sorry to be so dense here...

**Comment by evpobr** [comment]
> I use CMake at work so I am vaguely familiar with it, but I don't understand what advantage providing CMake to build WavPack would be.

CMake is well known today, it is wise to add support now. It allows easy integration between `wavpack` and any other CMake project.

It is better to leave Autotools untouched. Some Linux users (maintrainers?) will be happy. But with CMake you have Unix Makefiles with fast reconfiguration (CMake caches everything very efficiently), [Ninja backend](https://ninja-build.org/) for faster increment build. And also fancy colored output :-)

Visual Studio solution can be deprecated and removed later. It is hard to edit and keep it updated without Visual Studio installed. CMake can generate solution for any VS version from 6.0 to 2017. And [many more](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html).

Some IDEs [can open CMake directly](https://www.codeproject.com/Articles/1184735/Quick-Start-to-Use-Visual-Studio-Code-for-Cplusplu). Just open directory and that's all - you see project structure, you can build, debug and test. I can open Wavpack repo in Visual Studio Code on Windows platform, then open it on Linux platfrom. Everything just works. That's called [CMake server mode](https://cmake.org/cmake/help/latest/manual/cmake-server.7.html).

> I assume that the tarball would still use regular Make by default and that this change would provide an option for the user to select CMake on the configure command-line?

Tarball will work the same way. CMake has nothing to do with tarballs and can work from repo snapshot.  Some explanations about CMake's configure/build process in README is enough.

**Comment by jrlanglois** [comment]
CMake has its uses for sure! Whether it simplifies anything or not remains to be seen... Regardless, it is industry standard.

In fact, it's so standard that a third-party designed a scheme around supporting CMake based libraries as packages - [Hunter](https://github.com/ruslo/hunter). This is something we can also add to the CMake support process as it should make it easier for adoption.

**Comment by dbry** [comment]
I am not against this, and it looks like you put a lot of work into it. If you're willing to maintain it, I am happy to accept it. Thanks!
