### ISSUE TITLE
bugs found by our scanner

### ISSUE THREAD

**Issue by yuanqilbx** [dbry/WavPack#64]
Hi, we developed a taint analysis based static analysis tool named Vanguard. It could prognosis potential vulnerabilities by identifying security-sensitive operations (e.g. divide-zero, mod-zero, array-index-access, and sensitive function calls) without proper checks for their operands.

Some code locations are listed in the following. We think these locations maybe bugs after our manual analysis. Please check them, and add precondition checks if necessary.

**Bug-1:Div/Mod-zero**
1. in function `best_floating_line`,[pack_dns.c#L173](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/pack_dns.c#L173)
```c++
    center_y = (right_sum + left_sum) / num_values;
```
Divisor: num_values
			Result: Could be 0, Please Check.

2.in function `dynamic_noise_shaping`,[pack_dns.c#L87](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/pack_dns.c#L87)
```c++
        int max_allowed_error = 1000000 / wpc->ave_block_samples;
```
Divisor: wpc-&gt;ave_block_samples
			Result: Could be 0, Please Check.

3.in function `decorr_stereo_buffer`,[extra2.c#L365](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/extra2.c#L365)
```c++
    dppi->weight_B = dp.weight_B = dp.sum_B / num_samples;
```
Divisor: num_samples
			Result: Could be 0, Please Check.
			
4.in function `decorr_stereo_buffer`,[extra2.c#L364](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/extra2.c#L364)
```c++
    dppi->weight_A = dp.weight_A = dp.sum_A / num_samples;
```
Divisor: num_samples
			Result: Could be 0, Please Check.
			
3.in function `encode_buffer_fast`,[https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/pack_dsd.c#L406](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/pack_dsd.c#L406)
```c++
            mult = (high - low) / summed_probabilities [p0] [255];
```
Divisor: summed_probabilities[p0][255]
			Result: Could be 0, Please Check.

**Bug-2:security-senitive functions**
1.in function `find_header`,[ unpack_seek.c#L289](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/unpack_seek.c#L289)
```c++
                    memcpy (wphdr, sp - 4, sizeof (*wphdr));
```
[memcpy] is a memory operation function using tainted data: [wphdr  ]

2.in function `unpack_samples`,[unpack.c#L453](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/unpack.c#L453)
```c++
        memset (buffer, 0, sample_count * (flags & MONO_FLAG ? 4 : 8));
```
[memcpy] is a memory operation function using tainted data: [wps-&gt;block2buff  ]

3.in function `unpack_samples`,[ unpack.c#L96](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/unpack.c#L96)
```c++
            memset (buffer, 0, sample_count * 8);
```
[memset] is a memory operation function using tainted data: [buffer  ]

3.in function `unpack_samples`,[ unpack.c#L94](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/unpack.c#L94)
```c++
            memset (buffer, 0, sample_count * 4);
```
[memset] is a memory operation function using tainted data: [buffer  ]

4.in function `WavpackGetMD5Sum`,[open_utils.c#L871](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/open_utils.c#L871)
```c++
            memcpy (data, wpc->config.md5_checksum, 16);
```
[memcpy] is a memory operation function using tainted data: [data  ]

4.in function `process_metadata`,[open_utils.c#L775](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/open_utils.c#L775)
```c++
                memcpy (wpc->config.md5_checksum, wpmd->data, 16);
```

5.in function `calculate_probabilities`,[pack_dsd.c#L219](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/pack_dsd.c#L219)
```c++
        memset (probs, 0, sizeof (*probs) * 256);
```

6.in function `calculate_probabilities`,[pack_dsd.c#L220](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/pack_dsd.c#L220)
```c++
        memset (prob_sums, 0, sizeof (*prob_sums) * 256);
```

7.in function `create_riff_header`,[pack_utils.c#L880](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/pack_utils.c#L880)
```c++
    outptr = (char *) memcpy (outptr, &riffhdr, sizeof (riffhdr)) + sizeof (riffhdr);
```

8.in function `WavpackUnpackSamples`, [unpack_utils.c#L347](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/unpack_utils.c#L347)
```c++
memset (bptr, 0, samples_to_unpack * sizeof (*bptr));)
```

8.in function `WavpackUnpackSamples`, [unpack_utils.c#L333](https://github.com/dbry/WavPack/blob/9ccc3fe4a37d069137ceabe513a4dd9b0a09c1c2/src/unpack_utils.c#L333)
```c++
                    memset (bptr, 0, samples_to_unpack * num_channels * 4);
```

**Comment by jrlanglois** [comment]
Out of curiosity what bug scanner are you using? Looks useful. :slightly_smiling_face:

**Comment by stuartly** [comment]
@jrlanglois It is a static analysis tool named Vanguard, which is developed by our [team](https://github.com/SEG-SEC).  

Thanks
Lingyun Situ

**Comment by dbry** [comment]
Thanks very much for trying your tool on the WavPack code; it looks like it could be very useful indeed!

I looked over the bugs you suggested and I don't believe that any of them can actually be triggered or are legitimate vulnerabilities.

In the initial post you mentioned that bug-triggering files were attached, but I didn't see them, and now that post has been edited. If you _do_ have files that trigger any of these potential bugs I would very much like to see them as that would help me debug and fix them.

Thanks again!
