### ISSUE TITLE
5.1.0: gcc 9 compile warning 

### ISSUE THREAD

**Issue by kloczek** [dbry/WavPack#72]
In attachment is what is printed on stderr during building WavPack using gcc 9.
[wavpack.log](https://github.com/dbry/WavPack/files/3077248/wavpack.log)

**Comment by dbry** [comment]
Thanks for letting me know about these. There's obviously a bug in that version of gcc causing it to print exponentially increasing warnings...there's no reason that log needed to be 15 MB!

Anyway, I fixed all these on master.
