### ISSUE TITLE
unpack_samples crash on invalid multistream file

### ISSUE THREAD

**Issue by mark4o** [dbry/WavPack#8]
Unpacking an invalid WavPack multistream file can trigger an invalid memory access and crash, e.g. if the second stream contains no samples.

    Invalid read of size 2
       at 0x10005AF92: get_words_lossless (read_words.c:361)
       by 0x10006E263: unpack_samples (unpack.c:160)
       by 0x100076BC1: WavpackUnpackSamples (unpack_utils.c:246)
       by 0x100006096: main (wavpack.c:2872)
     Address 0x2 is not stack'd, malloc'd or (recently) free'd

The crash can be reproduced with git master (b02b134) and the command `wavpack in.wv -o out.wav` using the test case below, found by afl-fuzz.  This test case crashes in `getbit()`, called by `get_words_lossless()`, called by `unpack_samples()`, but similar test cases crash in `get_word()` or other functions called by `unpack_samples()`.

Test case (788 bytes, base64-encoded):
d3Zwa+QCAAAQBDAwMDAwMAAAAAAwMAAABQ8wMDAwMDACAVdWMAIwMDAwDQMwMAAwMDCKMAEAMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMHd2cGsgAAAAEAQwMDAwMDAwMDAwAAAAADAwMDAwMDAwMDAwMDAwMDA=

**Comment by dbry** [comment]
Thanks for reporting, fixed in "unicode" branch.
