### ISSUE TITLE
UBSan: left shift of negative value -1

### ISSUE THREAD

**Issue by andreafioraldi** [dbry/WavPack#81]
Running wavpack compiled with UBSan I get the following error:
`wavpack.c:3781:70: runtime error: left shift of negative value -1`

This is ofc undefined behavior due to the fact that you are shifting possible negative values in this line (and the following),
https://github.com/dbry/WavPack/blob/master/cli/wavpack.c#L3781

**Comment by dbry** [comment]
Thanks for reporting! Yes, I am very aware of the undefined behavior issues and and have been addressing those in libwavpack first, with the help of oss-fuzz. I will get to the ones in the command-line programs some time in the future.

**Comment by dbry** [comment]
I believe this is now fixed in master. Thanks again!
